create table if not exists public.species (
  id bigint generated by default as identity primary key,
  species_id text not null,
  name text not null,
  scientific_name text,
  rarity text not null,
  habitat text,
  description text,
  image_url text,
  icon_url text,
  is_active boolean default true,
  model_class_id integer,
  capture_enabled boolean not null default false,
  created_at timestamptz default timezone('utc', now())
);

create table if not exists public.discovery_cache (
  id bigint generated by default as identity primary key,
  wallet text not null,
  species_id bigint not null,
  grade integer not null,
  rarity text not null,
  proof_hash text,
  discovered_at timestamptz default timezone('utc', now()),
  perceptual_hash bit(64)
);